spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vanrin/config-repo
          force-pull: true
          default-label: main

  profiles:
    active: dev
  security:
    user:
      name: config-server
      password: 11223344
  application:
    name: config

server:
  port: 8888
